<script setup>
import { ref, computed, watch, onMounted, onBeforeUnmount } from 'vue';
const vModal={mounted:el=>el.showModal(),beforeUnmount:el=>el.close()};
const state=ref({drafts:[],accounts:[],media:[],publications:[],settings:{providers:{}}});
const page=ref('Drafts'), editor=ref(null), network=ref('shared'), search=ref(''), notice=ref(''), error=ref(''), saving=ref(false), syncing=ref(false), busy=ref(false), loaded=ref(false);
const recovery=ref(null), recoveryAction=ref('reschedule'), recoveryAt=ref(''), recoveryId=ref('');
const scheduleOpen=ref(false), scheduleMode=ref('exact'), scheduleAt=ref(''), email=ref(''), password=ref('');
const slotsAccount=ref(null), timezone=ref(Intl.DateTimeFormat().resolvedOptions().timeZone), slots=ref([]);
const csrf=document.querySelector('meta[name="csrf-token"]').content;
const names={x:'X',threads:'Threads',facebook:'Facebook',linkedin:'LinkedIn',linkedin_page:'LinkedIn Page'};
const symbols={x:'𝕏',threads:'@',facebook:'f',linkedin:'in',linkedin_page:'in'};
const clone=v=>JSON.parse(JSON.stringify(v));
const date=v=>new Date(v).toLocaleString(undefined,{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'});
let savePromise=null, pending=false, interval;
async function api(path,data,retried=false) {
 const response=await fetch('/local/'+path,{method:data===undefined?'GET':'POST',headers:{Accept:'application/json','X-CSRF-TOKEN':document.querySelector('meta[name="csrf-token"]').content,...(data instanceof FormData?{}:{'Content-Type':'application/json'})},body:data===undefined?undefined:data instanceof FormData?data:JSON.stringify(data)});
 if(response.status===419&&!retried){const fresh=await fetch('/local/csrf',{headers:{Accept:'application/json'}});if(fresh.ok){document.querySelector('meta[name="csrf-token"]').content=(await fresh.json()).token;return api(path,data,true);}}
 const result=await response.json(); if(!response.ok) throw new Error(Object.values(result.errors||{}).flat().join(' ')||result.message||'The request failed.'); return result;
}
async function refresh() { state.value=await api('state'); loaded.value=true; }
function report(e) { error.value=e.message; }
async function act(fn) { error.value='';busy.value=true;try { return await fn(); } catch(e) { report(e); } finally {busy.value=false;} }
function changed() { pending=true; flush().catch(report); }
async function flush() {
 if(savePromise) return savePromise;
 if(!pending || !editor.value) return;
 savePromise=(async()=>{ saving.value=true; try {
  while(pending && editor.value) { pending=false;const payload=clone(editor.value);const result=await api('drafts',payload);
   if(editor.value?.id===payload.id) editor.value.version=result.draft.version;
   const index=state.value.drafts.findIndex(d=>d.id===result.draft.id);
   if(index<0) state.value.drafts.unshift(result.draft);else state.value.drafts[index]=result.draft;
   if(result.conflict) { if(editor.value?.id===payload.id){editor.value.id=result.conflict.id;editor.value.version=result.conflict.version;} state.value.drafts.unshift(result.conflict);notice.value='Both versions were preserved. Your edit is saved as a conflict copy.'; }
  }
 } catch(e) { pending=true;throw e; } finally { saving.value=false;savePromise=null; }})();
 return savePromise;
}
async function openDraft(draft) { await act(async()=>{await flush();editor.value=clone(draft);network.value='shared';page.value='Drafts';}); }
async function newDraft() { await act(async()=>{await flush();editor.value={id:crypto.randomUUID(),title:'Untitled draft',version:0,content:{items:[{text:'',media_ids:[]}],overrides:{},account_ids:[]}};network.value='shared';page.value='Drafts';changed();}); }
const drafts=computed(()=>state.value.drafts.filter(d=>(d.title+' '+d.content.items.map(i=>i.text).join(' ')).toLowerCase().includes(search.value.toLowerCase())));
const items=computed(()=>editor.value ? network.value==='shared'?editor.value.content.items:editor.value.content.overrides[network.value]||editor.value.content.items:[]);
const chosen=computed(()=>state.value.accounts.filter(a=>editor.value?.content.account_ids.includes(a.id)));
const preview=computed(()=>{const target=chosen.value[0];let list=items.value; if(network.value==='shared' && target && ['facebook','linkedin','linkedin_page'].includes(target.provider))list=[{text:list.map(i=>i.text).join('\n\n'),media_ids:list.flatMap(i=>i.media_ids)}]; return list;});
const queue=computed(()=>state.value.publications.filter(p=>['scheduled','retry','publishing'].includes(p.status)).sort((a,b)=>new Date(a.scheduled_at)-new Date(b.scheduled_at)));
const history=computed(()=>state.value.publications.filter(p=>!['scheduled','retry','publishing'].includes(p.status)));
function customize(key) { network.value=key; if(key!=='shared'&&!editor.value.content.overrides[key]) { let base=clone(editor.value.content.items); if(['facebook','linkedin','linkedin_page'].includes(key))base=[{text:base.map(i=>i.text).join('\n\n'),media_ids:base.flatMap(i=>i.media_ids)}];editor.value.content.overrides[key]=base;changed(); } }
function resetOverride() {delete editor.value.content.overrides[network.value];network.value='shared';changed();}
function addPost() {items.value.push({text:'',media_ids:[]});changed();}
function removePost(i) {items.value.splice(i,1);changed();}
function attachment(id) {return state.value.media.find(m=>m.id===id);}
async function upload(event,index) {const files=Array.from(event.target.files);const target=items.value[index];await act(async()=>{for(const file of files){const data=new FormData();data.append('file',file);const media=await api('media',data);state.value.media.unshift(media);target.media_ids.push(media.id);changed();}await flush();});event.target.value='';}
function removeMedia(item,id) {item.media_ids=item.media_ids.filter(m=>m!==id);changed();}
async function sync(manual=true) { if(syncing.value||!state.value.settings.paired)return;syncing.value=true;try{await flush();const result=await api('sync',{});await refresh(); if(editor.value&&!pending&&!saving.value)editor.value=clone(state.value.drafts.find(d=>d.id===editor.value.id)||editor.value);if(manual)notice.value=result.conflicts?'Sync complete. Conflicting edits were saved as separate drafts.':'Everything is up to date.';}catch(e){if(manual)report(e);}finally{syncing.value=false;} }
async function schedule() {await act(async()=>{await flush();const payload={draft_id:editor.value.id,version:editor.value.version,mode:scheduleMode.value};if(payload.mode==='exact'){if(!scheduleAt.value)throw new Error('Choose a date and time.');payload.scheduled_at=new Date(scheduleAt.value).toISOString();}await api('schedule',payload);scheduleOpen.value=false;await refresh();notice.value='Confirmed by Sendae. Your post is in the queue.';page.value='Queue';});}
async function cancel(p) {await act(async()=>{await api('cancel',{id:p.id});await refresh();notice.value='Publication cancelled.';});}
async function signIn() {await act(async()=>{await flush();await api('signIn',{email:email.value,password:password.value});password.value='';await refresh();await sync();});}
async function signOut() {await act(async()=>{await flush();await api('signOut',{});await refresh();notice.value='Signed out. Your drafts are still saved on this Mac.';});}
function openRecovery(p) {recovery.value=p;recoveryAction.value=p.status==='uncertain'?'confirmed':'reschedule';recoveryAt.value='';recoveryId.value='';}
async function recover() {await act(async()=>{const payload={id:recovery.value.id,action:recoveryAction.value};if(payload.action==='confirmed')payload.post_id=recoveryId.value;else payload.scheduled_at=new Date(recoveryAt.value).toISOString();await api('recover',payload);recovery.value=null;await refresh();notice.value='Publication recovery saved.';});}
function postUrl(p,id) {const provider=accountFor(p)?.provider;return provider==='x'?'https://x.com/i/web/status/'+encodeURIComponent(id):provider==='facebook'?'https://www.facebook.com/'+encodeURIComponent(id):provider?.startsWith('linkedin')?'https://www.linkedin.com/feed/update/'+encodeURIComponent(id):null;}
function accountFor(p) {return state.value.accounts.find(a=>a.id===p.account_id);}
function connectionUrl(provider) {return state.value.settings.mode==='server'?'/connect/'+provider:(state.value.settings.paired?state.value.settings.connections_url+'/connect/'+provider:null);}
function editSlots(a) {slotsAccount.value=a;timezone.value=a.timezone;slots.value=clone(a.slots||[]);}
async function saveSlots() {await act(async()=>{await api('account',{id:slotsAccount.value.id,timezone:timezone.value,slots:slots.value});slotsAccount.value=null;await refresh();notice.value='Posting slots saved.';});}
async function disconnect(a) {if(!confirm('Disconnect '+a.name+' and cancel its queued publications?'))return;await act(async()=>{await api('disconnect',{id:a.id});await refresh();});}
async function refreshMetrics(p) {await act(async()=>{await api('analytics',{id:p.id});await refresh();});}
function keyboard(e) {if((e.metaKey||e.ctrlKey)&&e.key==='n'){e.preventDefault();newDraft();}if(e.key==='Escape'){scheduleOpen.value=false;slotsAccount.value=null;recovery.value=null;}}
function beforeUnload(e) {if(pending||saving.value){e.preventDefault();e.returnValue='';}}
onMounted(async()=>{await act(refresh);interval=setInterval(()=>sync(false),30000);window.addEventListener('beforeunload',beforeUnload);window.addEventListener('keydown',keyboard);});
onBeforeUnmount(()=>{clearInterval(interval);window.removeEventListener('beforeunload',beforeUnload);window.removeEventListener('keydown',keyboard);});
</script>

<template>
<div class="app-shell">
 <aside class="sidebar">
  <a href="#" class="brand" @click.prevent="page='Drafts'">sendae<span>✳</span></a>
  <div class="workspace-label"><span class="workspace-avatar">S</span><div>Personal workspace<small>A little more intentional.</small></div></div>
  <button class="primary new-draft" @click="newDraft">＋ <span>New draft</span><kbd>⌘ N</kbd></button>
  <nav aria-label="Main navigation"><button v-for="(icon,label) in {Drafts:'▤',Queue:'◷',Published:'↗',Analytics:'▥',Accounts:'◎'}" :class="{active:page===label}" @click="page=label"><span class="nav-icon">{{icon}}</span>{{label}}<span v-if="label==='Drafts'||label==='Queue'" class="count">{{label==='Drafts'?state.drafts.length:queue.length}}</span></button></nav>
  <div class="sidebar-bottom"><div class="quiet-note"><span>✳</span><p>Good things take a draft.<br><small>Make room for your next idea.</small></p></div><button class="settings-nav" :class="{active:page==='Settings'}" @click="page='Settings'">⚙ <span>Settings & connections</span></button><div class="sync-status"><i :class="{'connected':state.settings.paired||state.settings.mode==='server'}"></i>{{state.settings.mode==='server'?'Hosted workspace':state.settings.paired?'Connected to Sendae':'Saved on this Mac'}}<button v-if="state.settings.paired" @click="sync()" :disabled="syncing" aria-label="Synchronize now">↻</button></div></div>
 </aside>
 <main>
  <header><div class="breadcrumb">Workspace <span>/</span> <strong>{{page}}</strong></div><span class="header-note">A good day to put something out there.</span><span class="owner-avatar">You</span></header>
  <div v-if="error" class="banner error" role="alert">{{error}}<button @click="error=''" aria-label="Dismiss error">×</button></div>
  <div v-if="notice" class="banner success" role="status">{{notice}}<button @click="notice=''" aria-label="Dismiss message">×</button></div>
  <div v-if="!loaded" class="empty"><p>Opening your workspace…</p></div>
  <template v-else-if="page==='Drafts'">
   <div class="page-heading"><div><div class="eyebrow">YOUR WORDS, THEIR NEXT CHAPTER</div><h1>Drafts<span class="heading-dot">.</span></h1><p>A home for the ideas you haven’t shared. Yet.</p></div><button class="outline" @click="newDraft">＋ New draft</button></div>
   <div class="draft-layout" :class="{'has-editor':editor}">
    <section class="draft-list"><div class="list-toolbar"><span>All drafts <b>{{state.drafts.length}}</b></span><input v-model="search" type="search" placeholder="Search drafts…" aria-label="Search drafts"></div>
     <button v-for="draft in drafts" :key="draft.id" class="draft-card" :class="{selected:editor?.id===draft.id}" @click="openDraft(draft)"><div class="card-top"><span class="tag">{{draft.title.includes('(conflict copy)')?'Conflict copy':'Draft'}}</span><span>{{date(draft.updated_at)}}</span></div><h3>{{draft.title}}</h3><p>{{draft.content.items.map(i=>i.text).join(' ')||'A blank page. A small beginning.'}}</p><div class="card-footer"><span class="mini-networks"><span v-for="a in state.accounts.filter(a=>draft.content.account_ids.includes(a.id))" :key="a.id" :title="a.name">{{symbols[a.provider]}}</span><small v-if="!draft.content.account_ids.length">No destinations yet</small></span><small>{{draft.content.items.length>1?draft.content.items.length+' posts':'Single post'}} <span class="arrow">↗</span></small></div></button>
     <div v-if="!drafts.length&&!editor" class="empty draft-empty"><div class="empty-art">✳</div><h2>Every post starts somewhere.</h2><p>Catch a thought. Shape a story.<br>Your first draft is a click away.</p><button class="primary" @click="newDraft">Write your first draft <span>↗</span></button><div class="empty-tip">Text, images, video. One idea, every account.</div></div>
    </section>
    <section v-if="editor" class="composer"><div class="composer-top"><span>{{saving?'Saving…':pending?'Unsaved changes':state.settings.mode==='server'?'✓ Saved to server':'✓ Saved on this Mac'}}</span><button class="icon-button" @click="act(async()=>{await flush();editor=null})" aria-label="Close composer">×</button></div>
     <input class="title-input" aria-label="Draft title" v-model="editor.title" @input="changed" maxlength="200" placeholder="Give this idea a title">
     <div class="destinations"><label v-for="a in state.accounts.filter(a=>a.status==='connected')" :key="a.id" class="destination" :class="{checked:editor.content.account_ids.includes(a.id)}"><input type="checkbox" :value="a.id" v-model="editor.content.account_ids" @change="changed"><span class="network-icon">{{symbols[a.provider]}}</span>{{a.name}}</label><button v-if="!state.accounts.some(a=>a.status==='connected')" class="text-button" @click="page='Accounts'">＋ Connect your first account</button></div>
     <div class="network-tabs"><button :class="{active:network==='shared'}" @click="customize('shared')">Shared draft</button><button v-for="key in [...new Set(chosen.map(a=>a.provider))]" :key="key" :class="{active:network===key}" @click="customize(key)">{{names[key]}}<i v-if="editor.content.overrides[key]">•</i></button></div>
     <div v-if="network!=='shared'" class="override-note">Only {{names[network]}} uses this version.<button class="text-button" @click="resetOverride">Use shared draft</button></div>
     <div class="post-editor" v-for="(item,index) in items" :key="index"><div class="post-number"><span>{{String(index+1).padStart(2,'0')}}</span><button v-if="items.length>1" class="text-button" @click="removePost(index)" :aria-label="'Remove post '+(index+1)">Remove</button></div><textarea :aria-label="'Post '+(index+1)" v-model="item.text" @input="changed" placeholder="What’s on your mind?" rows="7"></textarea><div class="attachments"><div v-for="id in item.media_ids" :key="id" class="attachment"><video v-if="attachment(id)?.mime.startsWith('video/')" :src="'/local/media/'+id" controls></video><img v-else :src="'/local/media/'+id" :alt="attachment(id)?.name||'Attachment'"><button @click="removeMedia(item,id)" aria-label="Remove attachment">×</button></div></div><div class="editor-tools"><label class="upload-button">▧ <span>Attach media</span><input type="file" multiple accept="image/jpeg,image/png,image/webp,video/mp4,video/quicktime" @change="upload($event,index)" :disabled="busy"></label><span>{{Array.from(item.text).length}} characters</span></div></div>
     <button v-if="network==='shared'||['x','threads'].includes(network)" class="add-post" @click="addPost">＋ Add to thread</button>
     <details class="preview"><summary>Preview <span>How your words come together</span></summary><article v-for="(item,i) in preview" :key="i"><strong>{{chosen[0]?.name||'Your account'}}</strong><p>{{item.text||'Your post will appear here.'}}</p><small v-if="item.media_ids.length">{{item.media_ids.length}} attachment(s)</small></article><small>Network rendering may vary. LinkedIn and Facebook combine shared threads; select their tab to edit.</small></details>
     <footer class="composer-footer"><span>Make it yours. Then make it live.</span><button class="primary" @click="scheduleOpen=true" :disabled="busy||saving">Schedule <span>↗</span></button></footer>
    </section>
    <aside v-else-if="drafts.length" class="inspiration"><span>✳</span><h2>A little space<br>to think out loud.</h2><p>Open a draft to pick up where you left off, or start something new.</p></aside>
   </div>
  </template>
  <template v-else-if="page==='Queue'||page==='Published'">
   <div class="page-heading"><div><div class="eyebrow">{{page==='Queue'?'A RHYTHM THAT WORKS FOR YOU':'OUT IN THE WORLD'}}</div><h1>{{page==='Queue'?'Coming up':'Publication history'}}<span class="heading-dot">.</span></h1><p>{{page==='Queue'?'Confirmed posts, ready for their moment.':'Published posts and anything that needs your attention.'}}</p></div></div>
   <section class="content-section"><div v-for="p in page==='Queue'?queue:history" :key="p.id" class="publication-row"><span class="big-network">{{symbols[accountFor(p)?.provider]||'↗'}}</span><div class="publication-main"><h3>{{p.snapshot.title}}</h3><p>{{accountFor(p)?.name||'Disconnected account'}} · {{date(p.scheduled_at)}}</p><p v-if="p.error" class="error-text">{{p.error}}</p><div v-if="p.receipts?.length" class="receipt-links"><small>{{p.receipts.length}} confirmed post(s)</small><template v-for="(id,index) in p.receipts" :key="id"><a v-if="postUrl(p,id)" :href="postUrl(p,id)" target="_blank" rel="noopener">Post {{index+1}} ↗</a><code v-else>{{id}}</code></template></div></div><span class="tag" :class="p.status">{{p.status}}</span><button v-if="['failed','missed','uncertain','cancelled'].includes(p.status)" class="outline" @click="openRecovery(p)">Recover</button><button v-if="['scheduled','retry','failed','missed'].includes(p.status)" class="outline" @click="cancel(p)" :disabled="busy">Cancel</button></div><div v-if="!(page==='Queue'?queue:history).length" class="empty"><div class="empty-art">{{page==='Queue'?'◷':'↗'}}</div><h2>{{page==='Queue'?'Your next chapter is unwritten.':'Nothing published just yet.'}}</h2><p>{{page==='Queue'?'Schedule a draft for a specific time or add it to your weekly queue.':'Your publishing results will live here, including any posts that need help.'}}</p><button class="outline" @click="page='Drafts'">Back to drafts</button></div></section>
  </template>
  <template v-else-if="page==='Accounts'">
   <div class="page-heading"><div><div class="eyebrow">YOUR CORNERS OF THE INTERNET</div><h1>Accounts<span class="heading-dot">.</span></h1><p>Bring your people together. Keep each voice your own.</p></div></div>
   <section class="content-section"><div v-if="state.settings.mode!=='server'&&!state.settings.paired" class="setup-callout"><span>↗</span><div><h3>Sign in to start sharing.</h3><p>Sign in to Sendae to sync drafts and connect your social accounts.</p></div><button class="outline" @click="page='Settings'">Sign in</button></div><div class="account-grid"><article v-for="(label,key) in names" :key="key" class="account-card"><span class="big-network">{{symbols[key]}}</span><h2>{{label}}</h2><a v-if="connectionUrl(key)&&state.settings.providers[key]?.configured&&state.settings.providers[key]?.approved!==false" :href="connectionUrl(key)" target="_blank" rel="noopener" class="outline">Connect {{label}}</a><span v-else class="tag">{{state.settings.providers[key]?.configured&&state.settings.providers[key]?.approved===false?'Awaiting approval':(state.settings.mode!=='server'&&!state.settings.paired?'Sign in to connect':'Coming soon')}}</span></article></div><h2 v-if="state.accounts.length" class="section-title">Connected accounts</h2><div v-for="a in state.accounts" :key="a.id" class="publication-row"><span class="big-network">{{symbols[a.provider]}}</span><div class="publication-main"><h3>{{a.name}}</h3><p>{{names[a.provider]}} · {{a.timezone}} · {{a.slots?.length||0}} weekly slots</p></div><span class="tag">{{a.status}}</span><button class="outline" @click="editSlots(a)">Posting slots</button><button class="text-button" @click="disconnect(a)">Disconnect</button></div></section>
  </template>
  <template v-else-if="page==='Analytics'">
   <div class="page-heading"><div><div class="eyebrow">A LITTLE PERSPECTIVE</div><h1>How it’s landing<span class="heading-dot">.</span></h1><p>Engagement for posts shared through Sendae. Each network, in its own terms.</p></div></div><section class="content-section"><div class="analytics-note">Updated daily for 7 days, again at day 30, and whenever you refresh. Unavailable metrics stay unavailable.</div><article class="metrics-card" v-for="p in state.publications.filter(p=>p.status==='published')" :key="p.id"><div class="metrics-heading"><div><h3>{{p.snapshot.title}}</h3><p>{{accountFor(p)?.name}} · {{date(p.published_at)}}</p></div><button class="outline" @click="refreshMetrics(p)" :disabled="busy">Refresh</button></div><div class="metrics-grid"><div v-for="(value,key) in p.metrics||{views:null,likes:null,comments:null,reposts:null}" :key="key"><strong>{{value===null?'—':value.toLocaleString()}}</strong><span>{{key.replaceAll('_',' ')}}</span></div></div><small>{{p.metrics_status.replaceAll('_',' ')}} · {{p.metrics_refreshed_at?'Last checked '+date(p.metrics_refreshed_at):'Not refreshed yet'}}</small></article><div v-if="!state.publications.some(p=>p.status==='published')" class="empty"><div class="empty-art">▥</div><h2>Good stories find their people.</h2><p>Publish your first post to start seeing how it resonates.</p></div></section>
  </template>
  <template v-else-if="page==='Settings'">
   <div class="page-heading"><div><div class="eyebrow">MAKE YOURSELF AT HOME</div><h1>Settings<span class="heading-dot">.</span></h1><p>Your account, your words, wherever you are.</p></div></div>
   <section class="settings-content">
    <article class="settings-card"><h2>Your Sendae account</h2><p>Keep drafting offline. Sendae syncs your work and publishes scheduled posts while your Mac sleeps.</p>
     <template v-if="state.settings.mode!=='server'">
      <template v-if="state.settings.paired"><p>Signed in as <strong>{{state.settings.email}}</strong></p><button class="outline" @click="signOut" :disabled="busy">Sign out</button><details><summary>Sign in again</summary><form @submit.prevent="signIn"><label>Email<input v-model="email" type="email" autocomplete="username" required></label><label>Password<input v-model="password" type="password" autocomplete="current-password" required></label><button class="primary" :disabled="busy">Sign in</button></form></details></template>
      <form v-else @submit.prevent="signIn"><label>Email<input v-model="email" type="email" autocomplete="username" required></label><label>Password<input v-model="password" type="password" autocomplete="current-password" required></label><button class="primary" :disabled="busy">{{busy?'Signing in…':'Sign in to Sendae'}}</button><p class="muted">You can keep writing drafts without signing in.</p></form>
     </template>
     <form v-else method="post" action="/logout"><input type="hidden" name="_token" :value="csrf"><button class="outline">Sign out</button></form>
    </article>
    <article class="settings-card"><h2>Talk to your workspace</h2><p>Create drafts, attach media, schedule, cancel, and inspect analytics from Codex, ChatGPT, and Claude.</p><label>MCP connection<input readonly :value="state.settings.mcp_url"></label><p class="muted">Connect with your Sendae account. Social account credentials stay with Sendae.</p></article>
   </section>
  </template>
 </main>
 <dialog v-if="recovery" v-modal class="modal-backdrop" aria-labelledby="recovery-title" @cancel.prevent="recovery=null" @click.self="recovery=null"><section class="modal" aria-labelledby="recovery-title"><button class="modal-close" @click="recovery=null" aria-label="Close recovery">×</button><h2 id="recovery-title">Recover this publication</h2><p>{{recovery.snapshot.title}} · {{recovery.receipts?.length||0}} confirmed item(s) will be retained.</p><form @submit.prevent="recover"><label>Recovery action<select v-model="recoveryAction"><template v-if="recovery.status==='uncertain'"><option value="confirmed">I found the published post</option><option value="not_published">I verified that it was not published</option></template><option v-else value="reschedule">Reschedule unfinished items</option></select></label><label v-if="recoveryAction==='confirmed'">Provider post ID<input v-model="recoveryId" required placeholder="Post ID or LinkedIn URN"></label><label v-else>New date & time<input v-model="recoveryAt" type="datetime-local" required></label><p class="muted">Check the actual provider before resolving an uncertain outcome. Rescheduling an already published item can create a duplicate.</p><button class="primary" :disabled="busy">{{recoveryAction==='confirmed'?'Verify & record post':'Reschedule unfinished work'}}</button></form></section></dialog>
 <dialog v-if="scheduleOpen" v-modal class="modal-backdrop" aria-labelledby="schedule-title" @cancel.prevent="scheduleOpen=false" @click.self="scheduleOpen=false"><section class="modal" aria-labelledby="schedule-title"><button class="modal-close" @click="scheduleOpen=false" aria-label="Close scheduling">×</button><div class="eyebrow">GIVE IT A MOMENT</div><h2 id="schedule-title">Ready to share?</h2><p>Selected accounts: {{chosen.map(a=>a.name).join(', ')||'None. Select accounts in the composer.'}}</p><form @submit.prevent="schedule"><label>When should it go out?<select v-model="scheduleMode"><option value="exact">Choose a date & time</option><option value="queue">Next weekly slot per account</option><option value="now">Publish now</option></select></label><label v-if="scheduleMode==='exact'">Date & time · {{Intl.DateTimeFormat().resolvedOptions().timeZone}}<input v-model="scheduleAt" type="datetime-local" required></label><p class="muted">Scheduling requires confirmation from Sendae.</p><button class="primary" :disabled="busy||!chosen.length">{{busy?'Confirming…':scheduleMode==='now'?'Publish now':'Confirm schedule'}}</button></form></section></dialog>
 <dialog v-if="slotsAccount" v-modal class="modal-backdrop" aria-labelledby="slots-title" @cancel.prevent="slotsAccount=null" @click.self="slotsAccount=null"><section class="modal" aria-labelledby="slots-title"><button class="modal-close" @click="slotsAccount=null" aria-label="Close posting slots">×</button><h2 id="slots-title">A rhythm for {{slotsAccount.name}}</h2><form @submit.prevent="saveSlots"><label>Account timezone<input v-model="timezone" placeholder="Europe/London" required list="timezones"><datalist id="timezones"><option v-for="zone in Intl.supportedValuesOf('timeZone')" :value="zone" :key="zone"/></datalist></label><div v-for="(slot,index) in slots" :key="index" class="slot-row"><select v-model.number="slot.day" aria-label="Day"><option v-for="(day,i) in ['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday']" :value="i" :key="i">{{day}}</option></select><input type="time" v-model="slot.time" required aria-label="Posting time"><button type="button" class="icon-button" @click="slots.splice(index,1)" aria-label="Remove slot">×</button></div><button type="button" class="text-button" @click="slots.push({day:1,time:'09:00'})">＋ Add weekly slot</button><p class="muted">Slots follow the local clock through daylight saving changes. Actual dates appear in your queue.</p><button class="primary" :disabled="busy">Save posting slots</button></form></section></dialog>
</div>
</template>
